language: c

matrix:
  include:

    #### 8c4f8b0bffe02fbe030ecb17c9b7068cbc41850a
    - os: osx
      osx_image: xcode9.4
      env:
       - SIMH_CHECKOUT=8c4f8b0bffe02fbe030ecb17c9b7068cbc41850a
       - OENV="macOS 10.13 - xcode9.4"

    - os: osx
      osx_image: xcode10.2
      env:
       - SIMH_CHECKOUT=8c4f8b0bffe02fbe030ecb17c9b7068cbc41850a
       - OENV="macOS 10.14 - xcode10.2"

    - os: linux
      dist: xenial
      env:
       - SIMH_CHECKOUT=8c4f8b0bffe02fbe030ecb17c9b7068cbc41850a
       - OENV="Linux xenial"

    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=8c4f8b0bffe02fbe030ecb17c9b7068cbc41850a
       - OENV="Linux trusty"

#    - os: windows
#      env:
#       - SIMH_CHECKOUT=8c4f8b0bffe02fbe030ecb17c9b7068cbc41850a
#       - OENV="Windows"





script: 
   - ./script "${SIMH_CHECKOUT}"


