language: c

matrix:
  include:

    #### prev f9883668f1fdd724cb9930d113cac1e53774acd5 
    - os: osx
      osx_image: xcode9.4
      env:
       - SIMH_CHECKOUT=0b3e415b8ef97a64f2599a1d8ae811d760991db2
       - OENV="macOS 10.13 - xcode9.4"

    - os: osx
      osx_image: xcode10.2
      env:
       - SIMH_CHECKOUT=0b3e415b8ef97a64f2599a1d8ae811d760991db2
       - OENV="macOS 10.14 - xcode10.2"

    - os: linux
      dist: xenial
      env:
       - SIMH_CHECKOUT=0b3e415b8ef97a64f2599a1d8ae811d760991db2
       - OENV="Linux xenial"

    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=0b3e415b8ef97a64f2599a1d8ae811d760991db2
       - OENV="Linux trusty"

#    - os: windows ??
#      env:
#       - SIMH_CHECKOUT=f9883668f1fdd724cb9930d113cac1e53774acd5
#       - OENV="Windows"





script: 
   - ./script "${SIMH_CHECKOUT}"


