language: c

matrix:
  include:

    #### 6f5d8d3ed04fa38445b7a449d464f33d9a5d162c
    - os: osx
      osx_image: xcode9.4
      env:
       - SIMH_CHECKOUT=6f5d8d3ed04fa38445b7a449d464f33d9a5d162c
       - OENV="macOS 10.13 - xcode9.4"

    - os: osx
      osx_image: xcode10.2
      env:
       - SIMH_CHECKOUT=6f5d8d3ed04fa38445b7a449d464f33d9a5d162c
       - OENV="macOS 10.14 - xcode10.2"

    - os: linux
      dist: xenial
      env:
       - SIMH_CHECKOUT=6f5d8d3ed04fa38445b7a449d464f33d9a5d162c
       - OENV="Linux xenial"

    - os: linux
      dist: trusty
      env:
       - SIMH_CHECKOUT=6f5d8d3ed04fa38445b7a449d464f33d9a5d162c
       - OENV="Linux trusty"

#    - os: windows
#      env:
#       - SIMH_CHECKOUT=b3fa1f9fe8ff3858ee84f5e09f6b0ecff442378b
#       - OENV="Windows"





script: 
   - ./script "${SIMH_CHECKOUT}"


