version: 1.0

platform:
  - x86

image: Visual Studio 2022

cache:
  - ../windows-build

skip_commits:
  files:
    - .circleci/*

build: off

build_script:
  - script.cmd b0f160fc5ad44b843bb212462b1292004a3bebca
