#!/bin/bash

buildsimh() {
git clone https://github.com/simh/simh.git
cd simh
git checkout $1
make vax
cd ..
}

buildgzcompat() {
(
  echo '#include <stdlib.h>'
  tar -xOf compress/compress.tar ucb/compress/gzcompat.c
)>gzcompat.c

gcc -O -o gzcompat gzcompat.c
}

maketap() {
cat 4.3BSD-Quasijarus0c/miniroot.Z   | ./gzcompat | gzip -dc > miniroot

echo miniroot
cat 4.3BSD-Quasijarus0c/miniroot.Z   | ./gzcompat >a
ls -l a 
file a

cat 4.3BSD-Quasijarus0c/rootdump.Z   | ./gzcompat | gzip -dc > rootdump
cat 4.3BSD-Quasijarus0c/src.tar.Z    | ./gzcompat | gzip -dc > src.tar
cat 4.3BSD-Quasijarus0c/srcsys.tar.Z | ./gzcompat | gzip -dc > srcsys.tar
cat 4.3BSD-Quasijarus0c/stand.Z      | ./gzcompat | gzip -dc > stand
cat 4.3BSD-Quasijarus0c/usr.tar.Z    | ./gzcompat | gzip -dc > usr.tar
mkdisttap/mkdisttap.pl > quas.tap
}

writeinis() {
cat >config.ini <<__EOF__
SET CPU 64M
SET CPU IDLE=QUASIJARUS
set cr  dis
set lpt dis
set rl  dis
set ts  dis
set xq  dis
set rq0 ra82
att rq0 quas.dsk
set rq1 dis
set rq2 dis
set rq3 dis
att tq0 quas.tap
set tti 7b
set tto 7b
__EOF__

cat >rootdump.ini <<__EOF__
DO config.ini
EXPECT ">>>"               SEND "boot mua0:\r"                          ;GO
EXPECT "\r\n\n="           SEND "copy\r"                                ;GO
EXPECT "From: "            SEND "tms(0,1)\r"                            ;GO
EXPECT "To: "              SEND "ra(0,1)\r"                             ;GO
EXPECT "copied\n\r="       SEND "boot\r"                                ;GO
EXPECT "Boot\n\r: "        SEND "ra(0,1)vmunix\r"                       ;GO
EXPECT "root device? "     SEND "ra0*\r"                                ;GO
EXPECT "intr ^C\r\n# "     SEND \
"disklabel -rw ra0 ra82 \x22Quasijarus\x22 \
/usr/mdec/rdboot /usr/mdec/bootra\r"                                    ;GO
EXPECT "bootra\r\n# "      SEND "disk=ra0 type=ra82 tape=tms xtr\r"     ;GO
EXPECT "cassette\r\n# "    SEND "sync\x3B sync\x3B sync\r"              ;GO
EXPECT "sync\r\n# "       ;QUIT
BOOT CPU
__EOF__

cat >install.ini <<"__EOF__"
! rm -f nvram.dat
DO config.ini
ATT NVR nvram.dat
DEP BDR 1
EXPECT "Device? [XQA0]: "  SEND "dua0:\r" ;GO
EXPECT "intr ^C\r\n# "     SEND "newfs ra0g ra82\x3B newfs ra0h ra82\r" ;GO
EXPECT ",\r\n# "           SEND "mkdir /home\x3B mount /dev/ra0g /usr\r" ;GO
EXPECT "usr\r\n# "         SEND "cd /dev\x3B MAKEDEV tmscp0\x3B MAKEDEV dz0\r" ;GO
EXPECT "dz0\r\n# "         SEND "cd /usr\x3B mt rew\x3B mt fsf 3\x3B tar xvpbf 20 /dev/rmt12|sed '$!d'\r" ;GO
EXPECT "0b, 5120 bytes, 10 tape blocks\r\n# " SEND "mkdir src\x3B cd src\x3B mkdir sys\x3B cd sys\x3B mt fsf  \x3B tar xvpbf 20 /dev/rmt12|tail\r" ;GO
EXPECT "link to ../mdec/boot58/bootblk\r\n# " SEND "cd ..\x3B mt fsf  \x3B tar xvpbf 20 /dev/rmt12|tail\r" ;GO
EXPECT "ey.c, 712 bytes, 2 tape blocks\r\n# " SEND "echo \x22/dev/ra0a:/:rw:1:1|/dev/ra0h:/home:rw:1:3|/dev/ra0g:/usr:rw:1:2\x22 |tr '|' '\x5C012' >/etc/fstab\x3B shutdown -h now\r"; GO
BOOT CPU
QUIT
__EOF__

cat >sv.ini<<__EOF__
SHOW VERSION
QUIT
__EOF__

}

runit() {
simh/BIN/microvax3900 sv.ini
for c in 1 2 3 4 5 6 7 8; do
  echo ++++++++++ run $c $(date) ++++++++++
  rm -rf nvram.dat
  dd if=/dev/zero of=quas.dsk bs=512 count=1216665
  simh/BIN/microvax3900 rootdump.ini
  simh/BIN/microvax3900 install.ini
  echo ++++++++++++++++++++++++++++++++++++
  echo
done
}

main() {
buildsimh $1
buildgzcompat
maketap
writeinis
runit
}

((${#}-2))&&$1
((${#}-1))&&main $2
