version: 2.0
jobs:
  build-stretch:
    docker:
      - image: "debian:stretch"
    environment:
      SIMH_CHECKOUT: "331f6897470d9a53508ad42db2d27f76ec6ddf4d"
    steps:
      - checkout
      - run:  apt-get update -myq && apt-get install -my git make gcc libncurses-dev autoconf libsdl2-dev libpng-dev libpcap-dev libvdeplug-dev
      - run:
          name: build-stretch
          command: ./script try "${SIMH_CHECKOUT}"
          no_output_timeout: 10m
          timeout: 62m
      - store_artifacts:
          path: out
  build-jessie:
    docker:
      - image: "debian:jessie"
    environment:
      SIMH_CHECKOUT: "331f6897470d9a53508ad42db2d27f76ec6ddf4d"
    steps:
      - checkout
      - run:  apt-get update -myq && apt-get install -my git make gcc libncurses-dev autoconf libsdl2-dev libpng-dev libpcap-dev libvdeplug-dev
      - run:
          name: build-jessie
          command: ./script try "${SIMH_CHECKOUT}"
          no_output_timeout: 10m
          timeout: 62m
      - store_artifacts:
          path: out
workflows:
  version: 2
  build:
    jobs:
      - build-stretch
      - build-jessie
