version: 2.1

jobs:
  build-debian:
    docker:
      - image: debian:<< parameters.release >>
    parameters:
      release:
        type: enum
        enum: ["trixie", "bookworm"]
        default: "trixie"
    environment:
      SIMH_CHECKOUT: "b0f160fc5ad44b843bb212462b1292004a3bebca"
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
            apt-get update -qq && \
            apt-get install -y --no-install-recommends \
              git openssh-client make gcc libncurses-dev autoconf \
              libsdl2-dev libpng-dev libpcap-dev libvdeplug-dev
      - run:
          name: Build on Debian << parameters.release >>
          command: ./script try "${SIMH_CHECKOUT}"
          no_output_timeout: 10m
          timeout: 62m
      - store_artifacts:
          path: out

workflows:
  build:
    jobs:
      - build-debian:
          matrix:
            parameters:
              release: ["trixie", "bookworm"]
