version: 2.0
jobs:
  build_1:
    docker:
      - image: debian
    environment:
      SIMH_CHECKOUT: "9711fc017be7614a96ebe3759d779ab7de59bb96"
    steps:
      - checkout
      - run:
          name: build
          command: ./script try "${SIMH_CHECKOUT}"
          no_output_timeout: 10m
          timeout: 62m
      - store_artifacts:
          path: out
  build_2:
    docker:
      - image: debian-jessie
    environment:
      SIMH_CHECKOUT: "9711fc017be7614a96ebe3759d779ab7de59bb96"
    steps:
      - checkout
      - run:
          name: build
          command: ./script try "${SIMH_CHECKOUT}"
          no_output_timeout: 10m
          timeout: 62m
      - store_artifacts:
          path: out
workflows:
  version: 2
  build:
    jobs:
      - build_1
      - build_2
